// Site metadata and configuration constants

export const SITE = {
  name: "Archaic Horizon",
  description:
    "Electronic net label featuring a collection of experimental and ambient music",
  shortDescription: "Electronic music net label",
  url: process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
  creator: "@archaichorizon",
  email: "archaichorizon@gmail.com",
  keywords: [
    "electronic music",
    "ambient",
    "drone",
    "lo-fi",
    "minimal",
    "nostalgic",
    "experimental",
    "music label",
    "archaic horizon",
    "net label",
    "mp3",
    "free",
    "download",
    "stream",
    "listen",
    "free music",
    "free download",
    "free stream",
  ],
  authors: [{ name: "Archaic Horizon" }],
  category: "music",
  language: "en",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large" as const,
      "max-snippet": -1,
    },
  },
  openGraph: {
    type: "website" as const,
    locale: "en_US",
    siteName: "Archaic Horizon",
    defaultImage: {
      url: "/opengraph-image",
      width: 1200,
      height: 630,
      alt: "Archaic Horizon - Electronic Music Label",
    },
  },
  twitter: {
    card: "summary_large_image" as const,
    site: "@archaichorizon",
    creator: "@archaichorizon",
    images: {
      url: "/twitter-image",
      width: 1200,
      height: 630,
      alt: "Archaic Horizon - Electronic Music Label",
    },
  },
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
    ],
    shortcut: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
  manifest: "/site.webmanifest",
};
